// Package eula implements the vanilla-compatible EULA gate: the server
// refuses to start until the operator has accepted the Minecraft EULA,
// either via eula.txt or the --accept-eula flag.
package eula

import (
	_ "embed"
	"fmt"
	"os"
	"strings"
)

// Path is the conventional EULA file name, matching vanilla so existing
// tooling (panels, docker images, scripts) keeps working unchanged.
const Path = "eula.txt"

// embedded template mirrors vanilla's generated file.
const template = `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#You can also accept the EULA by passing --accept-eula on the command line.
#This file was generated by Gopherite.
eula=false
`

// State describes the current acceptance status.
type State int

const (
	// Missing means no eula.txt exists yet; Generate must run first.
	Missing State = iota
	// Rejected means eula.txt exists with eula=false.
	Rejected
	// Accepted means the operator agreed to the EULA.
	Accepted
)

// Check inspects the EULA state without modifying anything.
func Check(dir string) (State, error) {
	raw, err := os.ReadFile(join(dir, Path))
	if os.IsNotExist(err) {
		return Missing, nil
	}
	if err != nil {
		return Rejected, err
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "eula=") {
			if strings.TrimSpace(strings.TrimPrefix(line, "eula=")) == "true" {
				return Accepted, nil
			}
			return Rejected, nil
		}
	}
	return Rejected, nil
}

// Generate writes the default eula.txt (eula=false) into dir.
func Generate(dir string) error {
	return os.WriteFile(join(dir, Path), []byte(template), 0o644)
}

// Accept flips eula.txt to accepted, creating it if needed.
func Accept(dir string) error {
	if err := Generate(dir); err != nil {
		return err
	}
	return os.WriteFile(join(dir, Path), []byte(strings.Replace(template, "eula=false", "eula=true", 1)), 0o644)
}

// Ensure runs the vanilla gate: returns Accepted, or generates the file
// and returns a descriptive error telling the operator what to do.
func Ensure(dir string) (State, error) {
	st, err := Check(dir)
	if err != nil {
		return st, err
	}
	switch st {
	case Accepted:
		return Accepted, nil
	case Missing:
		if gerr := Generate(dir); gerr != nil {
			return Missing, gerr
		}
		return Missing, fmt.Errorf("eula: %s created; read https://aka.ms/MinecraftEULA and set eula=true (or restart with --accept-eula)", Path)
	default:
		return Rejected, fmt.Errorf("eula: %s has eula=false; you must agree to https://aka.ms/MinecraftEULA to run a server", Path)
	}
}

func join(dir, name string) string {
	if dir == "" {
		return name
	}
	return dir + "/" + name
}
