#!/usr/bin/env python3
"""Generate server/items_gen.go from the vanilla data reports.

Ground truth: reports/reports/registries.json (minecraft:item entries
carry the protocol id) and reports/reports/blocks.json (block name
universe). Run after a Minecraft version bump:

  python3 scripts/gen_items.py --reports reports/reports \
      --out server/items_gen.go

The item -> block placement mapping is derived by name equality with a
small, hand-audited exception table for the handful of vanilla items
whose placement target differs from their name (crops planted from
seeds, redstone dust, powder snow bucket, ...). Vanilla ground truth is
BlockItem#getBlock; the exceptions below were verified against the
runtime item registry dump of 26.2.
"""
import argparse
import json

# item name -> placed block, for items that place a block whose name
# differs from the item name.
ADD_BLOCK = {
    "minecraft:beetroot_seeds": "minecraft:beetroots",
    "minecraft:carrot": "minecraft:carrots",
    "minecraft:cocoa_beans": "minecraft:cocoa",
    "minecraft:glow_berries": "minecraft:cave_vines",
    "minecraft:melon_seeds": "minecraft:melon_stem",
    "minecraft:pitcher_pod": "minecraft:pitcher_crop",
    "minecraft:potato": "minecraft:potatoes",
    "minecraft:powder_snow_bucket": "minecraft:powder_snow",
    "minecraft:pumpkin_seeds": "minecraft:pumpkin_stem",
    "minecraft:redstone": "minecraft:redstone_wire",
    "minecraft:string": "minecraft:tripwire",
    "minecraft:sweet_berries": "minecraft:sweet_berry_bush",
    "minecraft:torchflower_seeds": "minecraft:torchflower_crop",
    "minecraft:wheat_seeds": "minecraft:wheat",
}

# items whose name matches a block but that place nothing (the block's
# asItem() is a different item).
DEL_BLOCK = {
    "minecraft:air",   # no placement
    "minecraft:wheat", # the crop block is placed by wheat_seeds
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reports", default="reports/reports")
    ap.add_argument("--out", default="server/items_gen.go")
    args = ap.parse_args()

    registries = json.load(open(f"{args.reports}/registries.json"))
    items = {k: v["protocol_id"]
             for k, v in registries["minecraft:item"]["entries"].items()}
    block_names = set(json.load(open(f"{args.reports}/blocks.json")))

    item_block = {}
    for name in items:
        if name in DEL_BLOCK:
            continue
        if name in ADD_BLOCK:
            item_block[name] = ADD_BLOCK[name]
        elif name in block_names:
            item_block[name] = name

    names = sorted(items, key=lambda n: items[n])

    with open(args.out, "w") as f:
        f.write("// Code generated by scripts/gen_items.py from the vanilla 26.2\n")
        f.write("// data reports (scripts/extract_vanilla_data.py); DO NOT EDIT.\n\n")
        f.write("package server\n\n")
        f.write("// itemIDByName maps \"minecraft:<item>\" to its item registry id.\n")
        f.write("var itemIDByName = map[string]int32{\n")
        pad = max(len(n) for n in names)
        for n in names:
            f.write(f'\t"{n}":'.ljust(len("\t") + pad + 3))
            f.write(f' {items[n]},\n')
        f.write("}\n\n")
        f.write("// itemBlockName maps placeable block items to their block id; the\n")
        f.write("// placement code resolves the block default state from here.\n")
        f.write("var itemBlockName = map[string]string{\n")
        bnames = sorted(item_block)
        bpad = max(len(n) for n in bnames)
        for n in bnames:
            f.write(f'\t"{n}":'.ljust(len("\t") + bpad + 3))
            f.write(f' "{item_block[n]}",\n')
        f.write("}\n")

    print(f"{len(items)} items, {len(item_block)} block items -> {args.out}")


if __name__ == "__main__":
    main()
