#!/usr/bin/env python3
"""Generate server/blocks_gen.go from the vanilla blocks report.

Ground truth: reports/reports/blocks.json produced by the vanilla data
generator (see scripts/extract_vanilla_data.py). Run after a Minecraft
version bump:

  python3 scripts/gen_blockstates.py --report reports/reports/blocks.json \
      --out server/blocks_gen.go

The tables cover every global block state id the protocol's chunk palette
can reference. blockNames is sorted so blockNameOf/defaultStateOf can
binary-search it.
"""
import argparse
import json


def emit_numeric(out, decl, comment, values, trailing_blank=True):
    if comment:
        out.write(f"// {comment}\n")
    out.write(f"var {decl} = []uint16{{\n")
    for i in range(0, len(values), 32):
        row = ", ".join(str(v) for v in values[i:i + 32])
        out.write(f"\t{row},\n")
    out.write("}\n" + ("\n" if trailing_blank else ""))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", default="reports/reports/blocks.json")
    ap.add_argument("--out", default="server/blocks_gen.go")
    args = ap.parse_args()

    blocks = json.load(open(args.report))
    names = sorted(blocks)

    # First encounter order over sorted blocks x report state order.
    props_index = {}
    props_table = []

    state_block = []   # indexed by global state id
    state_props = []   # indexed by global state id
    default_state = [] # indexed by blockNames index
    max_state = -1

    for bi, name in enumerate(names):
        entry = blocks[name]
        dflt = 0
        for si, st in enumerate(entry.get("states", [])):
            sid = st["id"]
            if st.get("default"):
                dflt = sid
            props = st.get("properties", {})
            key = ";".join(f"{k}={v}" for k, v in sorted(props.items()))
            pi = props_index.get(key)
            if pi is None:
                pi = len(props_table)
                props_index[key] = pi
                props_table.append(key)
            if sid >= len(state_block):
                state_block += [0] * (sid + 1 - len(state_block))
                state_props += [0] * (sid + 1 - len(state_props))
            state_block[sid] = bi
            state_props[sid] = pi
            max_state = max(max_state, sid)
        default_state.append(dflt)

    assert len(state_block) == max_state + 1, "gap in state id space"
    assert len(default_state) == len(names)

    with open(args.out, "w") as f:
        f.write("// Code generated by scripts/gen_blockstates.py from the vanilla 26.2\n")
        f.write("// blocks report; DO NOT EDIT.\n")
        f.write("//\n")
        f.write("// The table covers every global block state id the protocol's chunk\n")
        f.write("// palette can reference (id space = reports/reports/blocks.json).\n")
        f.write("package server\n\n")
        f.write("// blockNames lists every registered block, sorted by identifier, its\n")
        f.write("// index being referenced by stateBlock.\n")
        f.write("var blockNames = []string{\n")
        for n in names:
            f.write(f'\t"{n}",\n')
        f.write("}\n\n")
        emit_numeric(f, "stateBlock",
                     "stateBlock maps a global block state id to a blockNames index.",
                     state_block)
        f.write("// stateProps maps a state id to an index into propsTable\n")
        f.write("// (\"\" = no properties).\n")
        emit_numeric(f, "stateProps", None, state_props)
        f.write("// propsTable holds one \"k=v;k2=v2\" string per distinct\n")
        f.write("// property set, de-duplicated across all states.\n")
        f.write("var propsTable = []string{\n")
        for p in props_table:
            f.write(f'\t"{p}",\n')
        f.write("}\n\n")
        emit_numeric(f, "defaultState",
                     "defaultState maps a blockNames index to its default state id.",
                     default_state, trailing_blank=False)

    print(f"{len(names)} blocks, {max_state + 1} states, "
          f"{len(props_table)} distinct property sets -> {args.out}")


if __name__ == "__main__":
    main()
