#!/usr/bin/env python3
"""Generate server/items_gen.go from a runtime item-registry dump.

Ground truth: scripts/itemdump/DumpItems.java boots the vanilla 26.2
classes and prints every BuiltInRegistries.ITEM entry as
"<id> <item> <block>" (block = "-" for non-block items). Run it with:
  java -cp .:<libraries>/*:server-26.2.jar DumpItems
after a Minecraft version bump, then re-run this script.
"""
import sys

DUMP = "/home/z/my-project/research/ours-dump/items_clean.txt"
OUT = "/home/z/my-project/gopherite/server/items_gen.go"

items = []  # (id, item_name, block_name or None)
for line in open(DUMP):
    line = line.strip()
    if not line or line[0].isdigit() is False:
        continue
    parts = line.split(" ")
    if len(parts) != 3:
        continue
    idx, item, block = parts
    items.append((int(idx), item, None if block == "-" else block))

items.sort(key=lambda e: e[0])

with open(OUT, 'w') as f:
    f.write('// Code generated by scripts/gen_items.py from the runtime item\n')
    f.write('// registry dump of vanilla 26.2 (scripts/itemdump); DO NOT EDIT.\n\n')
    f.write('package server\n\n')
    f.write('// itemIDByName maps "minecraft:<item>" to its item registry id.\n')
    f.write('var itemIDByName = map[string]int32{\n')
    for idx, name, _ in items:
        f.write(f'\t"{name}": {idx},\n')
    f.write('}\n\n')
    f.write('// itemBlockName maps placeable block items to their block id; the\n')
    f.write('// placement code resolves the block default state from here.\n')
    f.write('var itemBlockName = map[string]string{\n')
    for _, name, block in items:
        if block is not None:
            f.write(f'\t"{name}": "{block}",\n')
    f.write('}\n')

print(f"{len(items)} items, {sum(1 for _,_,b in items if b)} block items -> {OUT}")
