package v776

import (
	_ "embed"
	"encoding/binary"
	"sync"

	"github.com/masgzy/gopherite/protocol/java"
)

//go:embed registry_data.bin
var registryDataBin []byte

var (
	registryOnce sync.Once
	registryPkts []java.ClientboundRegistryData
	registryErr  error
)

// RegistryDataPackets returns the fully populated Registry Data packets for
// every dynamically synchronised registry, in vanilla
// SYNCHRONIZED_REGISTRIES order. The payload is generated by
// scripts/gen_registry_nbt.py from the vanilla 26.2 server jar's bundled
// datapack; each entry carries its real network NBT so any client —
// vanilla or modded — can build the registries without relying on
// known-pack content elision.
func RegistryDataPackets() ([]java.ClientboundRegistryData, error) {
	registryOnce.Do(func() {
		registryPkts, registryErr = parseRegistryData(registryDataBin)
	})
	return registryPkts, registryErr
}

func parseRegistryData(blob []byte) ([]java.ClientboundRegistryData, error) {
	u8 := func() byte { v := blob[0]; blob = blob[1:]; return v }
	u16 := func() uint16 {
		v := binary.BigEndian.Uint16(blob[:2])
		blob = blob[2:]
		return v
	}
	u32 := func() uint32 {
		v := binary.BigEndian.Uint32(blob[:4])
		blob = blob[4:]
		return v
	}
	str8 := func() string {
		n := u8()
		s := string(blob[:n])
		blob = blob[n:]
		return s
	}

	count := int(u8())
	packets := make([]java.ClientboundRegistryData, 0, count)
	for range count {
		key := str8()
		entryCount := int(u16())
		entries := make([]java.RegistryEntry, 0, entryCount)
		for range entryCount {
			id := str8()
			n := int(u32())
			payload := make([]byte, n)
			copy(payload, blob[:n])
			blob = blob[n:]
			entries = append(entries, java.RegistryEntry{
				ID:      id,
				HasData: true,
				Payload: payload,
			})
		}
		packets = append(packets, java.ClientboundRegistryData{
			RegistryKey: key,
			Entries:     entries,
		})
	}
	return packets, nil
}
