// Package v776 implements the Minecraft Java Edition 26.2 protocol
// (protocol number 776).
//
// Packet identifiers are generated by registration order inside the vanilla
// ProtocolInfoBuilder chains, cross-verified against the official
// reports/packets.json emitted by the 26.2 data generator. Each packet id
// below has been taken from that report; do not hand-edit without
// regenerating the report.
package v776

// Version metadata.
const (
	Name              = "26.2"
	ProtocolNumber    = 776
	WorldVersion      = 4903
	DataPackVersion   = "107.1"
	ResourcePackMajor = 88
)

// Well-known namespace identifiers.
const (
	NamespaceVanilla = "minecraft"
	PackCoreID       = "core"
	BrandChannel     = "minecraft:brand"
)

// Serverbound packet identifiers, per connection state.
const (
	// Handshake state.
	PacketHandshake = 0x00

	// Status state.
	PacketStatusRequest = 0x00
	PacketPingRequest   = 0x01

	// Login state.
	PacketLSHello        = 0x00
	PacketLSKey          = 0x01
	PacketLSQueryAnswer  = 0x02
	PacketLSAcknowledged = 0x03
	PacketLSCookieReply  = 0x04

	// Configuration state.
	PacketConfigClientInfo   = 0x00
	PacketConfigCookieReply  = 0x01
	PacketConfigPayload      = 0x02
	PacketConfigFinish       = 0x03
	PacketConfigKeepAlive    = 0x04
	PacketConfigPong         = 0x05
	PacketConfigResourcePack = 0x06
	PacketConfigKnownPacks   = 0x07
	PacketConfigClickAction  = 0x08
	PacketConfigAcceptCOC    = 0x09

	// Play state.
	PacketPlayAcceptTeleport     = 0x00
	PacketPlaySBChatCommand      = 0x07
	PacketPlaySBChunkBatchDone   = 0x0B
	PacketPlayClientTickEnd      = 0x0D
	PacketPlayConfigAcknowledged = 0x10
	PacketPlaySBKeepAlive        = 0x1C
	PacketPlayPlayerAction       = 0x29
	PacketPlayMovePos            = 0x1E
	PacketPlayMovePosRot         = 0x1F
	PacketPlayMoveRot            = 0x20
	PacketPlayMoveStatus         = 0x21
	PacketPlayPlayerLoaded       = 0x2C
	PacketPlaySBPong             = 0x2D
	PacketPlaySBCarriedItem      = 0x35
	PacketPlaySwing              = 0x3F
	PacketPlayUseItemOn          = 0x42
	PacketPlaySBContainerButton  = 0x11
	PacketPlaySBContainerClick   = 0x12
	PacketPlaySBContainerClose   = 0x13
	PacketPlayPlayerInput        = 0x2B
	PacketPlaySetCreativeSlot    = 0x38
	PacketPlayUseItem            = 0x43
)

// Clientbound packet identifiers, per connection state.
const (
	// Status state.
	PacketStatusResponse = 0x00
	PacketPongResponse   = 0x01

	// Login state.
	PacketLoginDisconnect  = 0x00
	PacketLoginHello       = 0x01 // encryption request
	PacketLoginFinished    = 0x02 // login success
	PacketLoginCompression = 0x03
	PacketLoginCustomQuery = 0x04
	PacketLoginCookieReq   = 0x05

	// Configuration state.
	PacketCfgCookieRequest = 0x00
	PacketCfgPayload       = 0x01
	PacketCfgDisconnect    = 0x02
	PacketCfgFinish        = 0x03
	PacketCfgKeepAlive     = 0x04
	PacketCfgPing          = 0x05
	PacketCfgResetChat     = 0x06
	PacketCfgRegistryData  = 0x07
	PacketCfgPackPop       = 0x08
	PacketCfgPackPush      = 0x09
	PacketCfgStoreCookie   = 0x0A
	PacketCfgTransfer      = 0x0B
	PacketCfgFeatures      = 0x0C
	PacketCfgUpdateTags    = 0x0D
	PacketCfgKnownPacks    = 0x0E
	PacketCfgReportDetails = 0x0F
	PacketCfgServerLinks   = 0x10
	PacketCfgClearDialog   = 0x11
	PacketCfgShowDialog    = 0x12
	PacketCfgCodeOfConduct = 0x13

	// Play state.
	PacketPlayBundle           = 0x00
	PacketPlayAddEntity        = 0x01
	PacketPlayBossEvent        = 0x09
	PacketPlayBlockDestruction = 0x05
	PacketPlayBlockChangedAck  = 0x04
	PacketPlayBlockUpdate      = 0x08
	PacketPlayCBChunkBatchDone = 0x0B
	PacketPlayChunkBatchStart  = 0x0C
	PacketPlayDisconnect       = 0x20
	PacketPlayEntityEvent      = 0x22
	PacketPlayLevelParticles   = 0x2F
	PacketPlayPosSync          = 0x23
	PacketPlayGameEvent        = 0x26
	PacketPlayForgetChunk      = 0x25
	PacketPlayCBKeepAlive      = 0x2C
	PacketPlayLevelChunk       = 0x2D
	PacketPlayDifficulty       = 0x0A
	PacketPlayMoveEntityPos    = 0x35
	PacketPlayPayload          = 0x18
	PacketPlayLogin            = 0x31
	PacketPlayPing             = 0x3D
	PacketPlayAbilities        = 0x40
	PacketPlayPlayerInfo       = 0x46
	PacketPlayPlayerInfoRemove = 0x45
	PacketPlayPlayerPosition   = 0x48
	PacketPlayRemoveEntities   = 0x4D
	PacketPlayCacheCenter      = 0x5E
	PacketPlayCacheRadius      = 0x5F
	PacketPlaySetEntityData    = 0x63
	PacketPlaySetEntityMotion  = 0x65
	PacketPlaySpawnPosition    = 0x61
	PacketPlayHeldSlot         = 0x69
	PacketPlaySetPlayerInv     = 0x6C
	PacketPlayTakeItemEntity   = 0x7C
	PacketPlayCommands         = 0x10
	PacketPlayCBContainerClose = 0x11
	PacketPlayContainerContent = 0x12
	// M10: furnace burn/cook progress push (Container Set Data).
	PacketPlayContainerSetData = 0x13
	PacketPlayContainerSetSlot = 0x14
	PacketPlayOpenScreen       = 0x3B
	PacketPlaySetCursorItem    = 0x60
	PacketPlaySetTime          = 0x71
	PacketPlaySound            = 0x75
	PacketPlayExplode          = 0x24
	PacketPlaySystemChat       = 0x79
	PacketPlayTabList          = 0x7A
	PacketPlayUpdateTags       = 0x86

	// M8: survival + mobs (clientbound).
	PacketPlayAnimate          = 0x02
	PacketPlayDamageEvent      = 0x19
	PacketPlayHurtAnimation    = 0x2A
	PacketPlayMoveEntityPosRot = 0x36
	PacketPlayRotateHead       = 0x53
	PacketPlayRespawn          = 0x52
	PacketPlayPlayerCombatKill = 0x44
	PacketPlaySetExperience    = 0x67
	PacketPlaySetHealth        = 0x68
	PacketPlayUpdateAttributes = 0x83

	// M13: mob effects + thrown potions (clientbound).
	PacketPlayRemoveMobEffect = 0x4E
	PacketPlayUpdateMobEffect = 0x84

	// M16: scoreboard（packet_ids_776.txt 权威表）。
	PacketPlayResetScore          = 0x4F
	PacketPlaySetDisplayObjective = 0x62
	PacketPlaySetObjective        = 0x6A
	PacketPlaySetPlayerTeam       = 0x6D
	PacketPlaySetScore            = 0x6E

	// M16: world border（packet_ids_776.txt 权威表）。
	PacketPlayInitializeBorder      = 0x2B
	PacketPlaySetBorderCenter       = 0x58
	PacketPlaySetBorderLerpSize     = 0x59
	PacketPlaySetBorderSize         = 0x5A
	PacketPlaySetBorderWarningDelay = 0x5B
	PacketPlaySetBorderWarningDist  = 0x5C
)

// M13/M14 entity type ids (EntityTypes.register declaration order, 26.2).
const (
	EntityTypeAreaEffectCloud = 3   // minecraft:area_effect_cloud（第 4 个 register 调用）
	EntityTypeSplashPotion    = 105 // minecraft:splash_potion
	EntityTypeLingeringPotion = 106 // minecraft:lingering_potion
)

// M15 throwable projectile entity ids (EntityTypes.register declaration
// order, 26.2: SNOWBALL/EGG/ENDER_PEARL 第 121/40/45 个 register 调用)。
const (
	EntityTypeEgg        = 39  // minecraft:egg
	EntityTypeEnderPearl = 44  // minecraft:ender_pearl
	EntityTypeSnowball   = 120 // minecraft:snowball
)

// M8 serverbound combat/input packets.
const (
	PacketPlaySBAttack = 0x01
	// M16: signed 指令与 Tab 补全（packet_ids_776.txt 权威表）。
	PacketPlaySBChatCommandSigned = 0x08
	PacketPlaySBCommandSuggestion = 0x0F
	PacketPlayCBCommandSuggestion = 0x0F
	PacketPlaySBClientCommand     = 0x0C
	PacketPlaySBInteract          = 0x1A
	PacketPlaySBPlayerCommand     = 0x2A
)

// Entity type registry ids (protocol_id from reports/registries.json).
const (
	EntityTypeXPOrb         = 49  // minecraft:experience_orb
	EntityTypeItem          = 71  // minecraft:item
	EntityTypePlayer        = 156 // minecraft:player
	EntityTypeChicken       = 26  // minecraft:chicken
	EntityTypeCow           = 30  // minecraft:cow
	EntityTypePig           = 100 // minecraft:pig
	EntityTypeSheep         = 111 // minecraft:sheep
	EntityTypeZombie        = 151 // minecraft:zombie
	EntityTypeSkeleton      = 115 // minecraft:skeleton
	EntityTypeCreeper       = 32  // minecraft:creeper
	EntityTypeArrow         = 6   // minecraft:arrow
	EntityTypeTNT           = 133 // minecraft:tnt（26.2 registry_data.json 权威值）
	EntityTypeLightningBolt = 77  // minecraft:lightning_bolt
)

// Attribute registry ids (protocol_id from reports/registries.json).
const (
	AttributeKnockbackResistance = 20 // minecraft:knockback_resistance
	AttributeMaxHealth           = 23 // minecraft:max_health
	AttributeMovementSpeed       = 26 // minecraft:movement_speed
)

// Damage type registry ids. The damage_type registry is data-driven: the
// network id is the alphabetical position of data/minecraft/damage_type/
// <name>.json in the vanilla datapack (see gen_registries.py: sorted path
// = network id order).
const (
	DamageTypeDrown       = 6  // minecraft:drown
	DamageTypeFall        = 10 // minecraft:fall
	DamageTypeFreeze      = 17 // minecraft:freeze
	DamageTypeGeneric     = 18 // minecraft:generic
	DamageTypeGenericKill = 19 // minecraft:generic_kill
	DamageTypeInWall      = 22 // minecraft:in_wall
	DamageTypeLava        = 24 // minecraft:lava
	DamageTypeOutOfWorld  = 32 // minecraft:out_of_world
	DamageTypePlayerAtk   = 34 // minecraft:player_attack
	DamageTypeStarve      = 40 // minecraft:starve
	// M9 hostile mobs.
	DamageTypeArrow     = 0  // minecraft:arrow
	DamageTypeExplosion = 9  // minecraft:explosion
	DamageTypeMobAttack = 28 // minecraft:mob_attack
	DamageTypeInFire    = 21 // minecraft:in_fire
	DamageTypeOnFire    = 31 // minecraft:on_fire
	// M13 status effects.
	DamageTypeHotFloor      = 20 // minecraft:hot_floor
	DamageTypeIndirectMagic = 23 // minecraft:indirect_magic
	DamageTypeMagic         = 27 // minecraft:magic
	DamageTypeWither        = 49 // minecraft:wither
	// M15 投掷物：thrown 覆盖雪球/鸡蛋的命中（珍珠用 ender_pearl）。
	DamageTypeThrown     = 45 // minecraft:thrown
	DamageTypeEnderPearl = 8  // minecraft:ender_pearl
	// M16 世界边界：越界伤害（data/minecraft/damage_type 字母序第 34 个）。
	DamageTypeOutsideBorder = 33 // minecraft:outside_border
)

// SoundSource enum ordinals (net.minecraft.sounds.SoundSource order).
const (
	SoundSourceMaster  = 0
	SoundSourceMusic   = 1
	SoundSourceRecords = 2
	SoundSourceWeather = 3
	SoundSourceBlocks  = 4
	SoundSourceHostile = 5
	SoundSourceNeutral = 6
	SoundSourcePlayers = 7
	SoundSourceAmbient = 8
	SoundSourceVoice   = 9
)

// Entity metadata serializer ordinals (net.minecraft.network.syncher
// EntityDataSerializers registration order, stable since 1.13).
const (
	MetaSerializerByte         = 0
	MetaSerializerVarInt       = 1
	MetaSerializerFloat        = 3
	MetaSerializerBool         = 8
	MetaSerializerParticle     = 16 // 26.2 注册序：...BOOLEAN(8)...BLOCK_STATE(14)、OPTIONAL_BLOCK_STATE(15)、PARTICLE(16)
	MetaSerializerParticleList = 17
)

// Entity metadata indices used by M9. Index 0 is Entity.DATA_FLAGS for
// every entity (bit 0x01 = on fire); 16 is Creeper.DATA_SWELL_DIR. Both
// verified against the 26.2 SynchedEntityData.defineId declaration order
// (Entity 0-7, LivingEntity 8-14, Mob 15, Creeper 16-18).
const (
	MetaIndexEntityFlags  = 0
	MetaIndexCreeperSwell = 16
	EntityFlagOnFire      = 0x01
)

// M15 元数据：LivingEntity 的首个同步位（defineId 声明序，Entity 0-7、
// LivingEntity 8-14），0x01 = 幼年（AgeableMob.isBaby）。
const (
	MetaIndexLivingFlags = 8
	EntityFlagBaby       = 0x01
)

// M14 元数据索引。AreaEffectCloud 直接继承 Entity（基类 0-7），自身
// 依次定义 RADIUS(8)/WAITING(9)/PARTICLE(10)；AbstractArrow 在 Projectile
// 之上定义 FLAGS(8)/PIERCE_LEVEL(9)/IN_GROUND(10)，Arrow 再加
// EFFECT_COLOR(11)。对照 26.2 反编译源 defineId 声明序核验。
const (
	MetaIndexCloudRadius      = 8
	MetaIndexCloudWaiting     = 9
	MetaIndexCloudParticle    = 10
	MetaIndexArrowFlags       = 8
	MetaIndexArrowEffectColor = 11
	ArrowFlagCrit             = 0x01 // AbstractArrow.FLAG_CRIT
)

// 粒子注册表序号（ParticleTypes.register 声明序，26.2 反编译核验）：
// 0-27 依次为 angry_villager/block/.../end_rod，entity_effect = 28。
// entity_effect 载荷为 ColorParticleOption：一个 int32 ARGB 颜色。
const (
	ParticleEntityEffect = 28
	// M15：level_particles 直发的简单粒子（无载荷）。
	ParticlePortal = 67 // minecraft:portal（珍珠落点）
)

// PotionDefaultColor 是 PotionContents.getColor 的缺省值（无可见效果时）。
const PotionDefaultColor = int32(-13083194)
